version: '3.1'
services:
  db:
    container_name: typescript-boilerplate-db # Too prevent any container name conflict
    image: postgres:12-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: project

  redis:
    container_name: typescript-boilerplate-redis
    image: redis:6.0-alpine
    restart: always
    hostname: user
    command: redis-server --port 6379
    ports:
      - 6379:6379
